[tools]
bun = "latest"

[settings]
experimental = true

[hooks]
postinstall = "bun install"

[tasks.build]
run = "bun run tsc && bun run vite build"

[tasks.dev]
run = "bun run vite"

[tasks.preview]
run = "bun run vite preview"
